export const IMAGES={ 
    dashboard : new URL ( "../assets/dashboard.svg", import.meta.url).href,
    Audit : new URL ( "../assets/Audit.svg", import.meta.url).href,
    Analytics : new URL ( "../assets/Analytics.svg", import.meta.url).href,
    blog : new URL ( "../assets/blog.svg", import.meta.url).href,
    ccreation : new URL ( "../assets/ccreation.svg", import.meta.url).href,
    citation : new URL ( "../assets/citation.svg", import.meta.url).href,
    contentc : new URL ( "../assets/contentc.svg", import.meta.url).href,
    csuggestion : new URL ( "../assets/csuggestion.svg", import.meta.url).href,
    GLogo : new URL ( "../assets/GLogo.svg.svg", import.meta.url).href,
    KeyResearch : new URL ( "../assets/KeyResearch.svg", import.meta.url).href,
    keyword : new URL ( "../assets/keyword.svg", import.meta.url).href,
    logo : new URL ( "../assets/Logo.svg.svg", import.meta.url).href,
    profile : new URL ( "../assets/profile.svg", import.meta.url).href,
    settin : new URL ( "../assets/settin.svg", import.meta.url).href,
    setting : new URL ( "../assets/setting.svg", import.meta.url).href,
    Vectorlogout : new URL ( "../assets/Vectorlogout.svg", import.meta.url).href,
    WebAdt : new URL ( "../assets/WebAdt.svg", import.meta.url).href,
    WEBANA : new URL ( "../assets/WEBANA.svg", import.meta.url).href,
    Bell : new URL ( "../assets/Bell.png", import.meta.url).href,
    burger : new URL ( "../assets/burger.png", import.meta.url).href,
    Profile : new URL ( "../assets/Profile.png", import.meta.url).href,
    Setting : new URL ( "../assets/Setting.png", import.meta.url).href,
    graph : new URL ( "../assets/graph.png", import.meta.url).href,
    Mainimage : new URL ( "../assets/Mainimage.png", import.meta.url).href,
    Profiling : new URL ( "../assets/PROFILING.SVG", import.meta.url).href,
    competitor : new URL ( "../assets/COMPETITOR.SVG", import.meta.url).href,
    Article : new URL ( "../assets/ARTICLE WRITING.SVG", import.meta.url).href,
    chart : new URL ( "../assets/chart.svg", import.meta.url).href,


  envelopeIcon: new URL("../assets/email.svg", import.meta.url).href,
  coverimg: new URL("../assets/mainimg.png", import.meta.url).href,
  servicesimg: new URL("../assets/servicesimg.png", import.meta.url).href,
  keyres: new URL("../assets/keyres.png", import.meta.url).href,
  citsug: new URL("../assets/citsug.png", import.meta.url).href,
  webana: new URL("../assets/webana.png", import.meta.url).href,
  webaud: new URL("../assets/webaud.png", import.meta.url).href,
  directorimg: new URL("../assets/directorimg.png", import.meta.url).href,
  analystimg: new URL("../assets/analystimg.png", import.meta.url).href,
  attorneyimg: new URL("../assets/attorneyimg.png", import.meta.url).href,
  getstarted: new URL("../assets/getstarted.png", import.meta.url).href,
  group1: new URL("../assets/group1.svg", import.meta.url).href,
  group2: new URL("../assets/group2.svg", import.meta.url).href,
  group3: new URL("../assets/group3.svg", import.meta.url).href,
  group4: new URL("../assets/group4.svg", import.meta.url).href,
  group5: new URL("../assets/group5.svg", import.meta.url).href,
  group6: new URL("../assets/group6.svg", import.meta.url).href,
  arrowright: new URL("../assets/arrowright.svg", import.meta.url).href,
  hat: new URL("../assets/hat.svg", import.meta.url).href,
  shield: new URL("../assets/shield.svg", import.meta.url).href,
  apps: new URL("../assets/apps.svg", import.meta.url).href,
  facebook: new URL("../assets/facebook.svg", import.meta.url).href,
  twitter: new URL("../assets/twitter.svg", import.meta.url).href,
  instagram: new URL("../assets/instagram.svg", import.meta.url).href


  }